<a href="https://colab.research.google.com/github/AKSHTMISHRA/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing Numy dependency
import numpy as np
 

In [2]:
#1d array using a provided list 
list1=([1,2,3,4])
Numpy_arr=np.array(list1) 


In [3]:
Numpy_arr

array([1, 2, 3, 4])

In [6]:
#check type of numpy array 
type(Numpy_arr)


numpy.ndarray

In [4]:
#checking shape of the numpy array 
Numpy_arr.shape


(4,)

In [8]:
#reshaping the Numpy_arr
# copy() function 
arr=Numpy_arr.copy()
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [5]:
#checking the data type of the array 
Numpy_arr.dtype  

dtype('int64')

In [13]:
#2d Numpy array using given list
list1=([1,2,3,4])
list2=([5,6,7,8])
list3=([9,10,11,12]) 


In [18]:
d_arr=np.array([list1,list2,list3])

In [19]:
#checking the size 
d_arr.shape


(3, 4)

In [20]:
d_arr.dtype

dtype('int64')

In [22]:
#reshaping the d_arr
temp_d_arr=d_arr.copy()
temp_d_arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NOTE: 
while reshapeing  any 2-dimensional array it is to be kept in mind that
the arg1 and arg2 of reshaping    && the original arguments i.e. Oarg1,Oarg2
==> arg1 x arg2 == Oarg1 x Oarg2


In [26]:
##applicable
#temp_d_arr.reshape(1,12)
#temp_d_arr.reshape(2,6)
temp_d_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
#unapplicable
temp_d_arr.reshape(3,6)

ValueError: ignored