<a href="https://colab.research.google.com/github/AKSHTMISHRA/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing Numy dependency
import numpy as np
 

In [2]:
#1d array using a provided list 
list1=([1,2,3,4])
Numpy_arr=np.array(list1) 


In [3]:
Numpy_arr

array([1, 2, 3, 4])

In [6]:
#check type of numpy array 
type(Numpy_arr)


numpy.ndarray

In [4]:
#checking shape of the numpy array 
Numpy_arr.shape


(4,)

In [8]:
#reshaping the Numpy_arr
# copy() function 
arr=Numpy_arr.copy()
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [5]:
#checking the data type of the array 
Numpy_arr.dtype  

dtype('int64')

In [13]:
#2d Numpy array using given list
list1=([1,2,3,4])
list2=([5,6,7,8])
list3=([9,10,11,12]) 


In [18]:
d_arr=np.array([list1,list2,list3])

In [19]:
#checking the size 
d_arr.shape


(3, 4)

In [20]:
d_arr.dtype

dtype('int64')

In [22]:
#reshaping the d_arr
temp_d_arr=d_arr.copy()
temp_d_arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NOTE: 
while reshapeing  any 2-dimensional array it is to be kept in mind that
the arg1 and arg2 of reshaping    && the original arguments i.e. Oarg1,Oarg2
==> arg1 x arg2 == Oarg1 x Oarg2


In [26]:
##applicable
#temp_d_arr.reshape(1,12)
#temp_d_arr.reshape(2,6)
temp_d_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
#unapplicable
temp_d_arr.reshape(3,6)

ValueError: ignored

# INDEXING  in numpy array  




while indexing in a numpy array it should always  be remembered that the indexing in python always starts from 0.

In [29]:
#indexing 1d arr 
Numpy_arr


array([1, 2, 3, 4])

while using : based indexing 
numpy_array[arg1,arg2]
here,

*   arg1--> always inclusive
*   arg2--> always exclusive




In [32]:
#accesing random any element 
Numpy_arr[1]

2

In [33]:
Numpy_arr[:3]

array([1, 2, 3])

In [35]:
Numpy_arr[1:3]

array([2, 3])

In [38]:
Numpy_arr[:]
#   OR

array([1, 2, 3])

In [39]:
# indexing from back of the array 
Numpy_arr[:-1]
Numpy_arr[:-3]

array([1])

In [41]:
#indexing in 2d numpy array 
d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
#printing all the elements 
d_arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

while indexing in 2-dimensional Numpy array
---

Syntax: 2-Dimensinal_Numpy_Array[arg1:arg2,arg1*:arg2*]
1.   arg1,arg1* ==> always inclusive 
2.   arg2,arg2* ==> always exclusive


In [43]:
d_arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
d_arr[1:2,1:3]

array([[6, 7]])

In [46]:
d_arr[:-1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### creating NUMPY ARRAY on the go 
arange() function
syntax: arange(low,high,step=)
here,



1.   low- value always inclusive
2.   high- value always exclusive 
3.   step- difference between the values 




In [49]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [55]:
#linspace() function
#Return evenly spaced numbers over a specified interval.
np.linspace(1,10,50,dtype=int) 

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

### for values with conditions

In [56]:
Numpy_arr


array([1, 2, 3, 4])

In [57]:
Numpy_arr < 4

array([ True,  True,  True, False])

In [58]:
#for values
Numpy_arr[Numpy_arr<4]

array([1, 2, 3])

## array with values only 1's or 0's


*   ones() function
*   zeroes() funcion   


 