<a href="https://colab.research.google.com/github/AKSHTMISHRA/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
#importing Numy dependency
import numpy as np
 

In [70]:
#1d array using a provided list 
list1=([1,2,3,4])
Numpy_arr=np.array(list1) 


In [71]:
Numpy_arr

array([1, 2, 3, 4])

In [72]:
#check type of numpy array 
type(Numpy_arr)


numpy.ndarray

In [73]:
#checking shape of the numpy array 
Numpy_arr.shape


(4,)

In [74]:
#reshaping the Numpy_arr
# copy() function 
arr=Numpy_arr.copy()
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [75]:
#checking the data type of the array 
Numpy_arr.dtype  

dtype('int64')

In [76]:
#2d Numpy array using given list
list1=([1,2,3,4])
list2=([5,6,7,8])
list3=([9,10,11,12]) 


In [77]:
d_arr=np.array([list1,list2,list3])

In [78]:
#checking the size 
d_arr.shape


(3, 4)

In [79]:
d_arr.dtype

dtype('int64')

In [80]:
#reshaping the d_arr
temp_d_arr=d_arr.copy()
temp_d_arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NOTE: 
while reshapeing  any 2-dimensional array it is to be kept in mind that
the arg1 and arg2 of reshaping    && the original arguments i.e. Oarg1,Oarg2
==> arg1 x arg2 == Oarg1 x Oarg2


In [81]:
##applicable
#temp_d_arr.reshape(1,12)
#temp_d_arr.reshape(2,6)
temp_d_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [82]:
#unapplicable
temp_d_arr.reshape(3,6)

ValueError: ignored

# INDEXING  in numpy array  




while indexing in a numpy array it should always  be remembered that the indexing in python always starts from 0.

In [ ]:
#indexing 1d arr 
Numpy_arr


while using : based indexing 
numpy_array[arg1,arg2]
here,

*   arg1--> always inclusive
*   arg2--> always exclusive




In [ ]:
#accesing random any element 
Numpy_arr[1]

In [ ]:
Numpy_arr[:3]

In [ ]:
Numpy_arr[1:3]

In [ ]:
Numpy_arr[:]
#   OR

In [ ]:
# indexing from back of the array 
Numpy_arr[:-1]
Numpy_arr[:-3]

In [ ]:
#indexing in 2d numpy array 
d_arr

In [ ]:
#printing all the elements 
d_arr[:,:]

while indexing in 2-dimensional Numpy array
---

Syntax: 2-Dimensinal_Numpy_Array[arg1:arg2,arg1*:arg2*]
1.   arg1,arg1* ==> always inclusive 
2.   arg2,arg2* ==> always exclusive


In [ ]:
d_arr[1:]

In [ ]:
d_arr[1:2,1:3]

In [ ]:
d_arr[:-1]

### creating NUMPY ARRAY on the go 
arange() function
syntax: arange(low,high,step=)
here,



1.   low- value always inclusive
2.   high- value always exclusive 
3.   step- difference between the values 




In [ ]:
arr=np.arange(0,10)
arr

In [ ]:
arr=np.arange(0,10,step=2)
arr

In [ ]:
#linspace() function
#Return evenly spaced numbers over a specified interval.
np.linspace(1,10,50,dtype=int) 

### for values with conditions

In [ ]:
Numpy_arr


In [ ]:
Numpy_arr < 4

In [ ]:
#for values
Numpy_arr[Numpy_arr<4]

## array with values only 1's or 0's


*   ones() function
*   zeroes() funcion   


 

In [ ]:
np.ones(4)

In [ ]:
#1-d array 
np.ones(4,dtype=int)

In [ ]:
np.zeros(4,dtype=int)


In [ ]:
#2-d array 
np.ones((2,4),dtype=int)

In [ ]:
np.zeros((2,4),dtype=int)

## RANDOMLY SELECTED NUMPY ARRAYS 

In [ ]:
np.random.rand(3,3)



In [ ]:
np.random.randn(3,4)

In [ ]:
np.random.randint(1,100,8)