<a href="https://colab.research.google.com/github/AKSHTMISHRA/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing Numy dependency
import numpy as np
 

In [2]:
#1d array using a provided list 
list1=([1,2,3,4])
Numpy_arr=np.array(list1) 


In [3]:
Numpy_arr

array([1, 2, 3, 4])

In [4]:
#check type of numpy array 
type(Numpy_arr)


numpy.ndarray

In [5]:
#checking shape of the numpy array 
Numpy_arr.shape


(4,)

In [6]:
#reshaping the Numpy_arr
# copy() function 
arr=Numpy_arr.copy()
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [7]:
#checking the data type of the array 
Numpy_arr.dtype  

dtype('int64')

In [8]:
#2d Numpy array using given list
list1=([1,2,3,4])
list2=([5,6,7,8])
list3=([9,10,11,12]) 


In [9]:
d_arr=np.array([list1,list2,list3])

In [10]:
#checking the size 
d_arr.shape


(3, 4)

In [11]:
d_arr.dtype

dtype('int64')

In [12]:
#reshaping the d_arr
temp_d_arr=d_arr.copy()
temp_d_arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NOTE: 
while reshapeing  any 2-dimensional array it is to be kept in mind that
the arg1 and arg2 of reshaping    && the original arguments i.e. Oarg1,Oarg2
==> arg1 x arg2 == Oarg1 x Oarg2


In [13]:
##applicable
#temp_d_arr.reshape(1,12)
#temp_d_arr.reshape(2,6)
temp_d_arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
#unapplicable
temp_d_arr.reshape(3,6)

ValueError: ignored

# INDEXING  in numpy array  




while indexing in a numpy array it should always  be remembered that the indexing in python always starts from 0.

In [15]:
#indexing 1d arr 
Numpy_arr


array([1, 2, 3, 4])

while using : based indexing 
numpy_array[arg1,arg2]
here,

*   arg1--> always inclusive
*   arg2--> always exclusive




In [16]:
#accesing random any element 
Numpy_arr[1]

2

In [17]:
Numpy_arr[:3]

array([1, 2, 3])

In [18]:
Numpy_arr[1:3]

array([2, 3])

In [19]:
Numpy_arr[:]
#   OR

array([1, 2, 3, 4])

In [20]:
# indexing from back of the array 
Numpy_arr[:-1]
Numpy_arr[:-3]

array([1])

In [21]:
#indexing in 2d numpy array 
d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:

#printing all the elements 
d_arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

while indexing in 2-dimensional Numpy array
---

Syntax: 2-Dimensinal_Numpy_Array[arg1:arg2,arg1*:arg2*]
1.   arg1,arg1* ==> always inclusive 
2.   arg2,arg2* ==> always exclusive


In [23]:
d_arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
d_arr[1:2,1:3]

array([[6, 7]])

In [25]:
d_arr[:-1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### creating NUMPY ARRAY on the go 
arange() function
syntax: arange(low,high,step=)
here,



1.   low- value always inclusive
2.   high- value always exclusive 
3.   step- difference between the values 




In [26]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [28]:
#linspace() function
#Return evenly spaced numbers over a specified interval.
np.linspace(1,10,50,dtype=int) 

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

### for values with conditions

In [29]:
Numpy_arr


array([1, 2, 3, 4])

In [30]:
Numpy_arr < 4

array([ True,  True,  True, False])

In [31]:
#for values
Numpy_arr[Numpy_arr<4]

array([1, 2, 3])

## array with values only 1's or 0's


*   ones() function
*   zeroes() funcion   


 

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
#1-d array 
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [34]:
np.zeros(4,dtype=int)


array([0, 0, 0, 0])

In [35]:
#2-d array 
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## RANDOMLY SELECTED NUMPY ARRAYS 

Syntax: random.function( 

In [37]:
np.random.rand(3,3)

array([[0.78162708, 0.06287543, 0.77223005],
       [0.05636838, 0.28673026, 0.49693059],
       [0.4371451 , 0.44775259, 0.27128611]])

In [38]:
np.random.randn(3,4)

array([[-0.94598373, -1.17733198,  0.35156455,  0.0764945 ],
       [-0.84307812,  0.11405891,  2.69487179, -0.84615828],
       [ 1.17468956,  2.22574839,  0.14383007,  0.59944231]])

In [39]:
np.random.randint(1,100,8)

array([30, 77, 46, 75, 93, 41, 43, 47])

In [40]:
np.random.randint(1,100)

69

In [42]:
np.empty((2,4))

array([[4.66735061e-310, 2.14321575e-312, 2.37663529e-312,
        2.56761491e-312],
       [1.06099790e-312, 1.10343781e-312, 2.12199579e-312,
        0.00000000e+000]])

In [43]:
#addition of two numpy array 
arr1=np.arange(0,4)
arr2=np.arange(5,9)
print(arr1+arr2) 


[ 5  7  9 11]


In [44]:
#multiplication of two numpy array
print(arr2*arr1)

[ 0  6 14 24]


In [45]:
arr1*2

array([0, 2, 4, 6])

In [46]:
arr1

array([0, 1, 2, 3])